version: '3.8'

services:
  web:
    build: .
    container_name: multimarcas_brazo_app
    expose:
      - "80"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - PORT=${PORT:-80}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-True}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER:-noreply@brazo.com}
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
